<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ProjectType>Local</ProjectType>
    <ApplicationIcon>PERFEKTNA_Icon.ico</ApplicationIcon>
    <AssemblyKeyContainerName>
    </AssemblyKeyContainerName>
    <AssemblyOriginatorKeyFile>
    </AssemblyOriginatorKeyFile>
    <DefaultClientScript>JScript</DefaultClientScript>
    <DefaultHTMLPageLayout>Grid</DefaultHTMLPageLayout>
    <DefaultTargetSchema>IE50</DefaultTargetSchema>
    <DelaySign>false</DelaySign>
    <OutputType>WinExe</OutputType>
    <RunPostBuildEvent>OnBuildSuccess</RunPostBuildEvent>
    <StartupObject>kCalc.FormKCalc</StartupObject>
    <TargetZone>LocalIntranet</TargetZone>
    <GenerateManifests>false</GenerateManifests>
    <ApplicationManifest>Properties\app.manifest</ApplicationManifest>
    <IsWebBootstrapper>false</IsWebBootstrapper>
    <PublishUrl>publish\</PublishUrl>
    <Install>true</Install>
    <InstallFrom>Disk</InstallFrom>
    <UpdateEnabled>false</UpdateEnabled>
    <UpdateMode>Foreground</UpdateMode>
    <UpdateInterval>7</UpdateInterval>
    <UpdateIntervalUnits>Days</UpdateIntervalUnits>
    <UpdatePeriodically>false</UpdatePeriodically>
    <UpdateRequired>false</UpdateRequired>
    <MapFileExtensions>true</MapFileExtensions>
    <ApplicationRevision>0</ApplicationRevision>
    <ApplicationVersion>1.0.0.%2a</ApplicationVersion>
    <UseApplicationTrust>false</UseApplicationTrust>
    <BootstrapperEnabled>true</BootstrapperEnabled>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <UseWindowsForms>true</UseWindowsForms>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
    <AssemblyVersion>1.0.%2a</AssemblyVersion>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <BaseAddress>285212672</BaseAddress>
    <ConfigurationOverrideFile>
    </ConfigurationOverrideFile>
    <FileAlignment>4096</FileAlignment>
    <NoStdLib>false</NoStdLib>
    <NoWarn>
    </NoWarn>
    <RegisterForComInterop>false</RegisterForComInterop>
    <RemoveIntegerChecks>false</RemoveIntegerChecks>
    <UseVSHostingProcess>true</UseVSHostingProcess>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <BaseAddress>285212672</BaseAddress>
    <ConfigurationOverrideFile>
    </ConfigurationOverrideFile>
    <DebugSymbols>true</DebugSymbols>
    <FileAlignment>4096</FileAlignment>
    <NoStdLib>false</NoStdLib>
    <NoWarn>
    </NoWarn>
    <RegisterForComInterop>false</RegisterForComInterop>
    <RemoveIntegerChecks>false</RemoveIntegerChecks>
    <GenerateSerializationAssemblies>Auto</GenerateSerializationAssemblies>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="Microsoft.JScript">
      <EmbedInteropTypes>False</EmbedInteropTypes>
    </Reference>
    <Reference Include="Microsoft.Vsa">
      <Name>Microsoft.Vsa</Name>
      <HintPath>Microsoft.Vsa.dll</HintPath>
    </Reference>
    <Reference Include="PresentationFramework.Luna" />
    <Reference Update="System">
      <Name>System</Name>
    </Reference>
    <Reference Update="System.Core">
      <RequiredTargetFramework>3.5</RequiredTargetFramework>
    </Reference>
    <Reference Update="System.Data">
      <Name>System.Data</Name>
    </Reference>
    <Reference Update="System.Drawing">
      <Name>System.Drawing</Name>
    </Reference>
    <Reference Update="System.Xml">
      <Name>System.XML</Name>
    </Reference>
    <PackageReference Include="Acornima" Version="1.1.0" />
    <PackageReference Include="DynamicLanguageRuntime" Version="1.3.5" />
    <PackageReference Include="Esprima" Version="3.0.5" />
    <PackageReference Include="FSharp.Compiler.CodeDom" Version="1.0.0.1" />
    <PackageReference Include="FSharp.Core" Version="9.0.100" />
    <PackageReference Include="IronPython" Version="3.4.2" />
    <PackageReference Include="Jint" Version="4.1.0" />
    <PackageReference Include="Microsoft.Bcl.AsyncInterfaces" Version="9.0.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.Analyzers" Version="3.11.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.Common" Version="4.12.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.12.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Scripting" Version="4.12.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.Scripting.Common" Version="4.12.0" />
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyModel" Version="9.0.0" />
    <PackageReference Include="Microsoft.VisualBasic" Version="10.3.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="System.AppContext" Version="4.3.0" />
    <PackageReference Include="System.Buffers" Version="4.6.0" />
    <PackageReference Include="System.Collections" Version="4.3.0" />
    <PackageReference Include="System.Collections.Concurrent" Version="4.3.0" />
    <PackageReference Include="System.Collections.Immutable" Version="9.0.0" />
    <PackageReference Include="System.ComponentModel.Composition" Version="10.0.9" />
    <PackageReference Include="System.Console" Version="4.3.1" />
    <PackageReference Include="System.Data.DataSetExtensions" Version="4.5.0" />
    <PackageReference Include="System.Diagnostics.Debug" Version="4.3.0" />
    <PackageReference Include="System.Diagnostics.FileVersionInfo" Version="4.3.0" />
    <PackageReference Include="System.Diagnostics.StackTrace" Version="4.3.0" />
    <PackageReference Include="System.Diagnostics.Tools" Version="4.3.0" />
    <PackageReference Include="System.Dynamic.Runtime" Version="4.3.0" />
    <PackageReference Include="System.Globalization" Version="4.3.0" />
    <PackageReference Include="System.IO" Version="4.3.0" />
    <PackageReference Include="System.IO.Compression" Version="4.3.0" />
    <PackageReference Include="System.IO.FileSystem" Version="4.3.0" />
    <PackageReference Include="System.IO.FileSystem.Primitives" Version="4.3.0" />
    <PackageReference Include="System.IO.Pipelines" Version="9.0.0" />
    <PackageReference Include="System.Linq" Version="4.3.0" />
    <PackageReference Include="System.Linq.Expressions" Version="4.3.0" />
    <PackageReference Include="System.Memory" Version="4.6.0" />
    <PackageReference Include="System.Numerics.Vectors" Version="4.6.0" />
    <PackageReference Include="System.Reflection" Version="4.3.0" />
    <PackageReference Include="System.Reflection.Extensions" Version="4.3.0" />
    <PackageReference Include="System.Reflection.Metadata" Version="9.0.0" />
    <PackageReference Include="System.Resources.ResourceManager" Version="4.3.0" />
    <PackageReference Include="System.Runtime" Version="4.3.1" />
    <PackageReference Include="System.Runtime.CompilerServices.Unsafe" Version="6.1.0" />
    <PackageReference Include="System.Runtime.Extensions" Version="4.3.1" />
    <PackageReference Include="System.Runtime.InteropServices" Version="4.3.0" />
    <PackageReference Include="System.Runtime.InteropServices.RuntimeInformation" Version="4.3.0" />
    <PackageReference Include="System.Runtime.Loader" Version="4.3.0" />
    <PackageReference Include="System.Runtime.Numerics" Version="4.3.0" />
    <PackageReference Include="System.Security.Cryptography.Algorithms" Version="4.3.1" />
    <PackageReference Include="System.Security.Cryptography.Encoding" Version="4.3.0" />
    <PackageReference Include="System.Security.Cryptography.Primitives" Version="4.3.0" />
    <PackageReference Include="System.Security.Cryptography.X509Certificates" Version="4.3.2" />
    <PackageReference Include="System.Text.Encoding" Version="4.3.0" />
    <PackageReference Include="System.Text.Encoding.CodePages" Version="9.0.0" />
    <PackageReference Include="System.Text.Encoding.Extensions" Version="4.3.0" />
    <PackageReference Include="System.Text.Encodings.Web" Version="9.0.0" />
    <PackageReference Include="System.Text.Json" Version="9.0.0" />
    <PackageReference Include="System.Threading" Version="4.3.0" />
    <PackageReference Include="System.Threading.Tasks" Version="4.3.0" />
    <PackageReference Include="System.Threading.Tasks.Extensions" Version="4.6.0" />
    <PackageReference Include="System.Threading.Tasks.Parallel" Version="4.3.0" />
    <PackageReference Include="System.Threading.Thread" Version="4.3.0" />
    <PackageReference Include="System.ValueTuple" Version="4.5.0" />
    <PackageReference Include="System.Xml.ReaderWriter" Version="4.3.1" />
    <PackageReference Include="System.Xml.XDocument" Version="4.3.0" />
    <PackageReference Include="System.Xml.XmlDocument" Version="4.3.0" />
    <PackageReference Include="System.Xml.XPath" Version="4.3.0" />
    <PackageReference Include="System.Xml.XPath.XDocument" Version="4.3.0" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="dsVariables.cs">
      <DependentUpon>dsVariables.xsd</DependentUpon>
    </Compile>
    <Content Include="App.ico" />
    <Content Include="Calc.ico" />
    <Content Include="Documents\varijable_regex.txt" />
    <Content Include="Documents\Zadaci.txt" />
    <Content Include="PERFEKTNA_Icon.ico" />
    <Content Include="priprema\about.gif" />
    <Content Include="priprema\about.jpg" />
    <Content Include="priprema\background.jpg" />
    <None Update="About.rtf">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <Content Include="priprema\expences-button-png-hi.png" />
    <Content Include="priprema\icon\ni0043-48.gif" />
    <Content Include="priprema\icon\ni0044-48.gif" />
    <Content Include="priprema\icon\ni0045-48.gif" />
    <Content Include="priprema\icon\ni0046-48.gif" />
    <Content Include="priprema\icon\ni0048-48.gif" />
    <Content Include="priprema\icon\ni0069-48.gif" />
    <Content Include="priprema\icon\ni0104-48.gif" />
    <Content Include="priprema\icon\variables.png" />
    <Content Include="priprema\icon\wi0143-48.gif" />
    <Content Include="priprema\icon\wi0160-48.gif" />
    <Content Include="priprema\kalkulator_place.png" />
    <Content Include="priprema\nove boje.png" />
    <Content Include="priprema\nscript.sln" />
    <Content Include="priprema\open.gif" />
    <Content Include="priprema\open.ico" />
    <Content Include="priprema\open.jpg" />
    <Content Include="priprema\proba.gif" />
    <Content Include="priprema\ReservedWord_JavaScript.txt" />
    <Content Include="priprema\sample1.js" />
    <Content Include="priprema\save.gif" />
    <Content Include="priprema\save.ico" />
    <Content Include="priprema\save.jpg" />
    <Content Include="priprema\tipkaBar.jpg" />
    <Content Include="priprema\variables.png" />
    <Content Include="xFunction_CSHARP.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="xFunction_PYTHON.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="xFunction.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="icon\App.ico" />
    <Content Include="icon\Open.ico" />
    <Content Include="icon\save.ico" />
    <None Update="dsVariables.xsc">
      <DependentUpon>dsVariables.xsd</DependentUpon>
    </None>
    <None Update="dsVariables.xsd">
      <SubType>Designer</SubType>
      <Generator>MSDataSetGenerator</Generator>
      <LastGenOutput>dsVariables.Designer.cs</LastGenOutput>
    </None>
    <None Update="dsVariables.xss">
      <DependentUpon>dsVariables.xsd</DependentUpon>
    </None>
    <Content Include="ToDo.txt" />
  </ItemGroup>
  <ItemGroup>
    <None Include="priprema\Backup_of_tipka.cdr" />
    <None Include="priprema\kCalc GUI.cdr" />
    <None Include="priprema\lcdwintt.zip" />
    <None Include="priprema\setup\setup.vdproj" />
    <None Include="priprema\system.codedom.compiler.codedomprovider%28v=VS.100%29_aspx.mht" />
  </ItemGroup>
  <ItemGroup>
    <BootstrapperPackage Include="Microsoft.Net.Client.3.5">
      <Visible>False</Visible>
      <ProductName>.NET Framework 3.5 SP1 Client Profile</ProductName>
      <Install>false</Install>
    </BootstrapperPackage>
    <BootstrapperPackage Include="Microsoft.Net.Framework.2.0">
      <Visible>False</Visible>
      <ProductName>.NET Framework 2.0 %28x86%29</ProductName>
      <Install>false</Install>
    </BootstrapperPackage>
    <BootstrapperPackage Include="Microsoft.Net.Framework.3.0">
      <Visible>False</Visible>
      <ProductName>.NET Framework 3.0 %28x86%29</ProductName>
      <Install>false</Install>
    </BootstrapperPackage>
    <BootstrapperPackage Include="Microsoft.Net.Framework.3.5">
      <Visible>False</Visible>
      <ProductName>.NET Framework 3.5</ProductName>
      <Install>true</Install>
    </BootstrapperPackage>
    <BootstrapperPackage Include="Microsoft.Net.Framework.3.5.SP1">
      <Visible>False</Visible>
      <ProductName>.NET Framework 3.5 SP1</ProductName>
      <Install>false</Install>
    </BootstrapperPackage>
    <BootstrapperPackage Include="Microsoft.Windows.Installer.3.1">
      <Visible>False</Visible>
      <ProductName>Windows Installer 3.1</ProductName>
      <Install>true</Install>
    </BootstrapperPackage>
  </ItemGroup>
  <ItemGroup>
    <WCFMetadata Include="Service References\" />
  </ItemGroup>
  <ItemGroup Label="Compile items now included by globbing that were not in the original project file">
    <Compile Remove="priprema\nscript\ConsoleApp.cs" />
    <Compile Remove="priprema\nscript\AssemblyInfo.cs" />
    <Compile Remove="priprema\nscriptw\WindowsApp.cs" />
    <Compile Remove="priprema\nscriptw\AssemblyInfo.cs" />
    <Compile Remove="priprema\nscript.lib\UnsupportedLanguageExecption.cs" />
    <Compile Remove="priprema\nscript.lib\ScriptManager.cs" />
    <Compile Remove="priprema\nscript.lib\IScriptManagerCallback.cs" />
    <Compile Remove="priprema\nscript.lib\IScriptManager.cs" />
    <Compile Remove="priprema\nscript.lib\CompilerError.cs" />
    <Compile Remove="priprema\nscript.lib\BaseApp.cs" />
    <Compile Remove="priprema\nscript.lib\AssemblyInfo.cs" />
    <Compile Remove="priprema\cs-script\samples\WinForm.cs" />
    <Compile Remove="priprema\cs-script\samples\unsafe_keyword.cs" />
    <Compile Remove="priprema\cs-script\samples\tick.cs" />
    <Compile Remove="priprema\cs-script\samples\SurrogateHostScript.cs" />
    <Compile Remove="priprema\cs-script\samples\ScriptEncryption\Script.cs" />
    <Compile Remove="priprema\cs-script\samples\ScriptEncryption\host.cs" />
    <Compile Remove="priprema\cs-script\samples\ScriptEncryption\CRC32.cs" />
    <Compile Remove="priprema\cs-script\samples\ScriptEE.cs" />
    <Compile Remove="priprema\cs-script\samples\Sandboxing\NET4.0\UntrustedCode.cs" />
    <Compile Remove="priprema\cs-script\samples\Sandboxing\NET4.0\Host\UntrustedCode.cs" />
    <Compile Remove="priprema\cs-script\samples\Sandboxing\NET4.0\Host\Host.cs" />
    <Compile Remove="priprema\cs-script\samples\Sandboxing\NET4.0\Host\ExpressionSerializer.cs" />
    <Compile Remove="priprema\cs-script\samples\Sandboxing\NET4.0\Host\AssemblyInfo.cs" />
    <Compile Remove="priprema\cs-script\samples\Sandboxing\NET4.0\Host.cs" />
    <Compile Remove="priprema\cs-script\samples\Sandboxing\HostSimlified.cs" />
    <Compile Remove="priprema\cs-script\samples\Sandboxing\Host.cs" />
    <Compile Remove="priprema\cs-script\samples\Sandboxing\Danger1.cs" />
    <Compile Remove="priprema\cs-script\samples\Sandboxing\Danger.cs" />
    <Compile Remove="priprema\cs-script\samples\RuntimeInfo.cs" />
    <Compile Remove="priprema\cs-script\samples\runScript.cs" />
    <Compile Remove="priprema\cs-script\samples\REST\WebAPI_Server.cs" />
    <Compile Remove="priprema\cs-script\samples\Resources\Script.cs" />
    <Compile Remove="priprema\cs-script\samples\ReflectScript.cs" />
    <Compile Remove="priprema\cs-script\samples\Progressbar.cs" />
    <Compile Remove="priprema\cs-script\samples\printScreen.cs" />
    <Compile Remove="priprema\cs-script\samples\Precompilers\Script.cs" />
    <Compile Remove="priprema\cs-script\samples\Precompilers\nuget_update.cs" />
    <Compile Remove="priprema\cs-script\samples\Precompilers\freestyle.cs" />
    <Compile Remove="priprema\cs-script\samples\Precompilers\AdvancedSamples\Precompilers\hashdef.cs" />
    <Compile Remove="priprema\cs-script\samples\Precompilers\AdvancedSamples\Precompilers\dsl.cs" />
    <Compile Remove="priprema\cs-script\samples\Precompilers\AdvancedSamples\Precompilers\auto_method.cs" />
    <Compile Remove="priprema\cs-script\samples\Precompilers\AdvancedSamples\Precompilers\auto_class.cs" />
    <Compile Remove="priprema\cs-script\samples\Precompilers\AdvancedSamples\freestyle_dsl.cs" />
    <Compile Remove="priprema\cs-script\samples\Precompilers\AdvancedSamples\CPPHashDef.cs" />
    <Compile Remove="priprema\cs-script\samples\Precompilers\AdvancedSamples\classless.cs" />
    <Compile Remove="priprema\cs-script\samples\nkill.cs" />
    <Compile Remove="priprema\cs-script\samples\Macros\script_simple.cs" />
    <Compile Remove="priprema\cs-script\samples\Macros\script.cs" />
    <Compile Remove="priprema\cs-script\samples\Macros\precompile.cs" />
    <Compile Remove="priprema\cs-script\samples\importTickScript.cs" />
    <Compile Remove="priprema\cs-script\samples\Hosting\Scripting.native.cs" />
    <Compile Remove="priprema\cs-script\samples\Hosting\Scripting.Extensions.cs" />
    <Compile Remove="priprema\cs-script\samples\Hosting\Scripting.evaluator.cs" />
    <Compile Remove="priprema\cs-script\samples\Hosting\Legacy Samples\CompilerAsService\MemoryManagement.cs" />
    <Compile Remove="priprema\cs-script\samples\Hosting\Legacy Samples\CompilerAsService\HostingScenarios.cs" />
    <Compile Remove="priprema\cs-script\samples\Hosting\Legacy Samples\CompilerAsService\Hello.cs" />
    <Compile Remove="priprema\cs-script\samples\Hosting\Legacy Samples\CodeDOM\VS2012 project\Script.cs" />
    <Compile Remove="priprema\cs-script\samples\Hosting\Legacy Samples\CodeDOM\VS2012 project\Host.cs" />
    <Compile Remove="priprema\cs-script\samples\Hosting\Legacy Samples\CodeDOM\VS2012 project\AssemblyInfo.cs" />
    <Compile Remove="priprema\cs-script\samples\Hosting\Legacy Samples\CodeDOM\VS2010 project\Script.cs" />
    <Compile Remove="priprema\cs-script\samples\Hosting\Legacy Samples\CodeDOM\VS2010 project\Host.cs" />
    <Compile Remove="priprema\cs-script\samples\Hosting\Legacy Samples\CodeDOM\VS2010 project\AssemblyInfo.cs" />
    <Compile Remove="priprema\cs-script\samples\Hosting\Legacy Samples\CodeDOM\VS2008 project\Script.cs" />
    <Compile Remove="priprema\cs-script\samples\Hosting\Legacy Samples\CodeDOM\VS2008 project\AssemblyInfo.cs" />
    <Compile Remove="priprema\cs-script\samples\Hosting\Legacy Samples\CodeDOM\TypeSafety.cs" />
    <Compile Remove="priprema\cs-script\samples\Hosting\Legacy Samples\CodeDOM\RuntimeErrors.cs" />
    <Compile Remove="priprema\cs-script\samples\Hosting\Legacy Samples\CodeDOM\Referencing\VS2008 project\Script.cs" />
    <Compile Remove="priprema\cs-script\samples\Hosting\Legacy Samples\CodeDOM\Referencing\VS2008 project\Host.cs" />
    <Compile Remove="priprema\cs-script\samples\Hosting\Legacy Samples\CodeDOM\Referencing\VS2008 project\AssemblyInfo.cs" />
    <Compile Remove="priprema\cs-script\samples\Hosting\Legacy Samples\CodeDOM\Referencing\Script.cs" />
    <Compile Remove="priprema\cs-script\samples\Hosting\Legacy Samples\CodeDOM\Referencing\Host.cs" />
    <Compile Remove="priprema\cs-script\samples\Hosting\Legacy Samples\CodeDOM\Referencing\ExternalAsm.cs" />
    <Compile Remove="priprema\cs-script\samples\Hosting\Legacy Samples\CodeDOM\Performance.cs" />
    <Compile Remove="priprema\cs-script\samples\Hosting\Legacy Samples\CodeDOM\Older versions of CLR\Host.cs" />
    <Compile Remove="priprema\cs-script\samples\Hosting\Legacy Samples\CodeDOM\Older versions of CLR\AssemblyInfo.cs" />
    <Compile Remove="priprema\cs-script\samples\Hosting\Legacy Samples\CodeDOM\NonC#CompilerInHostApp.cs" />
    <Compile Remove="priprema\cs-script\samples\Hosting\Legacy Samples\CodeDOM\Non C# scripts\HostVBScript.cs" />
    <Compile Remove="priprema\cs-script\samples\Hosting\Legacy Samples\CodeDOM\Non C# scripts\host.cs" />
    <Compile Remove="priprema\cs-script\samples\Hosting\Legacy Samples\CodeDOM\Modifying script without restart\Script.cs" />
    <Compile Remove="priprema\cs-script\samples\Hosting\Legacy Samples\CodeDOM\Modifying script without restart\Host.cs" />
    <Compile Remove="priprema\cs-script\samples\Hosting\Legacy Samples\CodeDOM\MethodSignatures.cs" />
    <Compile Remove="priprema\cs-script\samples\Hosting\Legacy Samples\CodeDOM\LifetimeManagement.cs" />
    <Compile Remove="priprema\cs-script\samples\Hosting\Legacy Samples\CodeDOM\InterfaceAlignment\InterfaceAlignmentWithoutScripting.cs" />
    <Compile Remove="priprema\cs-script\samples\Hosting\Legacy Samples\CodeDOM\InterfaceAlignment\Host.cs" />
    <Compile Remove="priprema\cs-script\samples\Hosting\Legacy Samples\CodeDOM\InterfaceAlignment\HelloScript.cs" />
    <Compile Remove="priprema\cs-script\samples\Hosting\Legacy Samples\CodeDOM\InterfaceAlignment\ExtendingLife.cs" />
    <Compile Remove="priprema\cs-script\samples\Hosting\Legacy Samples\CodeDOM\HostVBScript.cs" />
    <Compile Remove="priprema\cs-script\samples\Hosting\Legacy Samples\CodeDOM\HostingWithInterfaces\Script.cs" />
    <Compile Remove="priprema\cs-script\samples\Hosting\Legacy Samples\CodeDOM\HostingWithInterfaces\Host.cs" />
    <Compile Remove="priprema\cs-script\samples\Hosting\Legacy Samples\CodeDOM\HostingSimplified\Script.cs" />
    <Compile Remove="priprema\cs-script\samples\Hosting\Legacy Samples\CodeDOM\HostingSimplified\Host.cs" />
    <Compile Remove="priprema\cs-script\samples\Hosting\Legacy Samples\CodeDOM\Hello.cs" />
    <Compile Remove="priprema\cs-script\samples\Hosting\Legacy Samples\CodeDOM\Eval.cs" />
    <Compile Remove="priprema\cs-script\samples\Hosting\Legacy Samples\CodeDOM\DetectingScriptCodeCalls\Script.cs" />
    <Compile Remove="priprema\cs-script\samples\Hosting\Legacy Samples\CodeDOM\DetectingScriptCodeCalls\Host.cs" />
    <Compile Remove="priprema\cs-script\samples\Hosting\Legacy Samples\CodeDOM\Debugging.cs" />
    <Compile Remove="priprema\cs-script\samples\Hosting\Legacy Samples\CodeDOM\CustomProbing.cs" />
    <Compile Remove="priprema\cs-script\samples\Hosting\Legacy Samples\CodeDOM\ConditionalCompilation.cs" />
    <Compile Remove="priprema\cs-script\samples\Hosting\Legacy Samples\CodeDOM\CompileErrors.cs" />
    <Compile Remove="priprema\cs-script\samples\Hosting\Legacy Samples\CodeDOM\Classless.cs" />
    <Compile Remove="priprema\cs-script\samples\Hosting\Legacy Samples\CodeDOM\AppDomainExtensions.cs" />
    <Compile Remove="priprema\cs-script\samples\Hosting\HostingScenarios.cs" />
    <Compile Remove="priprema\cs-script\samples\Hosting\Hello.cs" />
    <Compile Remove="priprema\cs-script\samples\hello_auto.cs" />
    <Compile Remove="priprema\cs-script\samples\hello.cs" />
    <Compile Remove="priprema\cs-script\samples\getUrl.cs" />
    <Compile Remove="priprema\cs-script\samples\ErrorLevelTester.cs" />
    <Compile Remove="priprema\cs-script\samples\cutfile.cs" />
    <Compile Remove="priprema\cs-script\samples\code.Net_v4.5.cs" />
    <Compile Remove="priprema\cs-script\samples\Code.cs" />
    <Compile Remove="priprema\cs-script\samples\Classless\Standalone script\HelloWorld.cs" />
    <Compile Remove="priprema\cs-script\samples\Classless\Hostied script\ExecuteClasslessWithDefaultCompiler.cs" />
    <Compile Remove="priprema\cs-script\samples\Automation\Script.cs" />
    <Compile Remove="priprema\cs-script\samples\Automation\App.cs" />
    <Compile Remove="priprema\cs-script\lib\verify.cs" />
    <Compile Remove="priprema\cs-script\lib\nuget_update.cs" />
    <Compile Remove="priprema\cs-script\lib\lsnuget.cs" />
    <Compile Remove="priprema\cs-script\lib\lscache.cs" />
    <Compile Remove="priprema\cs-script\lib\help.cs" />
    <Compile Remove="priprema\cs-script\lib\debugVS14.0.cs" />
    <Compile Remove="priprema\cs-script\lib\debugVS12.0.cs" />
    <Compile Remove="priprema\cs-script\lib\debugVS11.0.cs" />
    <Compile Remove="priprema\cs-script\lib\debugVS10.0.cs" />
    <Compile Remove="priprema\cs-script\lib\config.cs" />
    <Compile Remove="priprema\cs-script\lib\clearTemp.cs" />
    <Compile Remove="priprema\cs-script\inc\who.cs" />
    <Compile Remove="priprema\cs-script\inc\which.cs" />
    <Compile Remove="priprema\cs-script\inc\WebApi.cs" />
    <Compile Remove="priprema\cs-script\inc\ServiceStack.cs" />
    <Compile Remove="priprema\cs-script\inc\pkill.cs" />
    <Compile Remove="priprema\cs-script\inc\isadmin.cs" />
    <Compile Remove="priprema\cs-script\hello.cs" />
  </ItemGroup>
  <ItemGroup Label="EmbeddedResource items now included by globbing that were not in the original project file">
    <EmbeddedResource Remove="priprema\nscript.lib\NScript.resx" />
  </ItemGroup>
</Project>