//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kCalc.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.3.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color FormForeColor {
            get {
                return ((global::System.Drawing.Color)(this["FormForeColor"]));
            }
            set {
                this["FormForeColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tahoma, 9pt")]
        public global::System.Drawing.Font myFont {
            get {
                return ((global::System.Drawing.Font)(this["myFont"]));
            }
            set {
                this["myFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("64, 0, 0")]
        public global::System.Drawing.Color PanelColor {
            get {
                return ((global::System.Drawing.Color)(this["PanelColor"]));
            }
            set {
                this["PanelColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("64, 0, 0")]
        public global::System.Drawing.Color FormBackColor {
            get {
                return ((global::System.Drawing.Color)(this["FormBackColor"]));
            }
            set {
                this["FormBackColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tahoma, 9pt")]
        public global::System.Drawing.Font myFontScriptBox {
            get {
                return ((global::System.Drawing.Font)(this["myFontScriptBox"]));
            }
            set {
                this["myFontScriptBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Gold")]
        public global::System.Drawing.Color myFontScriptBoxColor {
            get {
                return ((global::System.Drawing.Color)(this["myFontScriptBoxColor"]));
            }
            set {
                this["myFontScriptBoxColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point FormKCalcLocation {
            get {
                return ((global::System.Drawing.Point)(this["FormKCalcLocation"]));
            }
            set {
                this["FormKCalcLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RFile1 {
            get {
                return ((string)(this["RFile1"]));
            }
            set {
                this["RFile1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RFile2 {
            get {
                return ((string)(this["RFile2"]));
            }
            set {
                this["RFile2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RFile3 {
            get {
                return ((string)(this["RFile3"]));
            }
            set {
                this["RFile3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RFile4 {
            get {
                return ((string)(this["RFile4"]));
            }
            set {
                this["RFile4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RFile5 {
            get {
                return ((string)(this["RFile5"]));
            }
            set {
                this["RFile5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public uint RFilePointer {
            get {
                return ((uint)(this["RFilePointer"]));
            }
            set {
                this["RFilePointer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SaveObjects {
            get {
                return ((bool)(this["SaveObjects"]));
            }
            set {
                this["SaveObjects"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Microsoft Sans Serif, 10.2pt")]
        public global::System.Drawing.Font myPrinterFont {
            get {
                return ((global::System.Drawing.Font)(this["myPrinterFont"]));
            }
            set {
                this["myPrinterFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Microsoft Sans Serif, 18pt, style=Bold")]
        public global::System.Drawing.Font myFontDisplay {
            get {
                return ((global::System.Drawing.Font)(this["myFontDisplay"]));
            }
            set {
                this["myFontDisplay"] = value;
            }
        }
    }
}
